### ISSUE TITLE
关于disqus评论的问题

### ISSUE THREAD

**Issue by KaitoHH** [szcf-weiya/ESL-CN#162]
你好！首先感谢一下对ESL这本书的翻译，正好我也在学这门课，能看到对这本书的详细解读真的对我很有帮助！
我想问一个和ESL没那么相关的问题，我注意到你的ESL网站中的`disqus`评论系统，似乎针对国内无法访问`disqus`的问题专门进行了优化，能否请问一下你是如何处理的呢？因为我的博客之前也用了`disqus`作评论系统，但因为国内无法直接访问只能弃用了。谢谢！

**Comment by szcf-weiya** [comment]
你好！我是用了 [fooleap/disqus-php-api](https://github.com/fooleap/disqus-php-api)，而且在我的[技术笔记](https://tech.hohoweiya.xyz/website/#disqus_1)中记录了一些有用的参考链接。

**Comment by KaitoHH** [comment]
好的！感谢提供的链接！让我再仔细研究一下，谢谢！

**Comment by szcf-weiya** [comment]
没事，希望能帮助到你~
