### ISSUE TITLE
这是怎么计算得来的

### ISSUE THREAD

**Issue by duniang818** [szcf-weiya/ESL-CN#193]
Since this corresponds to a fraction r of the unit volume,
the expected edge length will be e p (r) = r 1/p . In ten dimensions e 10 (0.01) =
0.63 and e 10 (0.1) = 0.80,

**Comment by szcf-weiya** [comment]
The volume of a $p$-dimensional hypercube is 
$$
V = c_p r^p
$$
where $c_p$ is a constant. Then for the unit hypercube, the volume is $c_p$, and hence the fraction is $r^p$. So ...
