### ISSUE TITLE
MARS一节存在部分数学公式未能正常显示

### ISSUE THREAD

**Issue by szcf715** [szcf-weiya/ESL-CN#2]
![selection_483](https://user-images.githubusercontent.com/19305558/28367190-74de4536-6cc2-11e7-9459-5ab586929f12.png)

**Comment by szcf715** [comment]
![selection_484](https://user-images.githubusercontent.com/19305558/28367196-7e6b8ff0-6cc2-11e7-8d6d-6e430e3b83e0.png)

**Comment by szcf715** [comment]
![selection_485](https://user-images.githubusercontent.com/19305558/28367203-8592bbc8-6cc2-11e7-8efb-bec072dc5c0d.png)

**Comment by szcf-weiya** [comment]
@szcf715 fixed!
