### ISSUE TITLE
Github Pages 404

### ISSUE THREAD

**Issue by byby221b** [szcf-weiya/ESL-CN#222]
您好，https://esl.hohoweiya.xyz/ 网站大部分页面似乎都404了，是否出了什么问题
![image](https://user-images.githubusercontent.com/34156234/77763850-ac74a980-7076-11ea-8139-517434f98d09.png)

**Comment by szcf-weiya** [comment]
@byby221b 具体网页地址？或者刷新重试下，换不同运营商试试，比如用手机？我这边测试都是可以正常访问的。今天上午我确实调整了下域名解析，但应该立即就生效了。

**Comment by byby221b** [comment]
现在可以打开了，多谢了
