### ISSUE TITLE
Chapter 1.1 - Website URL of ESL is unavailable

### ISSUE THREAD

**Issue by laplacetw** [szcf-weiya/ESL-CN#248]
I've found another website:
[https://hastie.su.domains/ElemStatLearn/](https://hastie.su.domains/ElemStatLearn/)

**Comment by szcf-weiya** [comment]
Thanks for pointing. 
I think they are the same website, just use a new domain. Just had a try, https://web.stanford.edu/~hastie would be automatically redirected to https://hastie.su.domains/
