### ISSUE TITLE
Can you tell me how the recursive computational spline basis functions of Computations for Splines (B-splines) can be used on natural cubic spline?

### ISSUE THREAD

**Issue by abraxas126** [szcf-weiya/ESL-CN#254]
I'm more confused as to which N(X) of the natural spline the recursively derived basis function corresponds to

**Comment by szcf-weiya** [comment]
you can check the appendix of chapter 5 
https://esl.hohoweiya.xyz/05-Basis-Expansions-and-Regularization/Appendix-Computations-for-B-splines/index.html#_2

**Comment by szcf-weiya** [comment]
for the detailed relation between B-spline basis and natural spline basis, you can check Exercise 2.5 of Hastie, T., & Tibshirani, R. (1990). Generalized additive models. Chapman & Hall.

![image](https://github.com/szcf-weiya/ESL-CN/assets/13688320/e5ae4e5e-38ec-4a8e-9675-86780465b904)

**Comment by abraxas126** [comment]
> you can check the appendix of chapter 5 https://esl.hohoweiya.xyz/05-Basis-Expansions-and-Regularization/Appendix-Computations-for-B-splines/index.html#_2

Yes, I was looking at exactly the recursive method for the B-spline basis function in the appendix. The previous article was mentioning that saying M is very large can lead to unstable numerical calculations on a computer with lots of rounding errors.
So I thought of:
1. Is the third power of the natural cubic spline considered very large? Will it cause rounding errors?
2. To calculate the basis function of the natural cubic spline, should I use this recursive calculation method?
3. How does the recursive basis function result correspond to the original basis function of the natural cubic spline?

**Comment by szcf-weiya** [comment]
- degree = 4 (i.e., power = 3 as you said) is a quite popular choice, not too large or too small. Where did you find that there would be lots of rounding errors?
- Of course, you should use the recursive formula since it is exactly the definition.
- you will get your answer by solving the following exercise. In a word, there exists a matrix Z such that N = BZ, in other words, you can simply perform transformation as in general linear algebra.

> for the detailed relation between B-spline basis and natural spline basis, you can check Exercise 2.5 of Hastie, T., & Tibshirani, R. (1990). Generalized additive models. Chapman & Hall.
> 
> ![image](https://user-images.githubusercontent.com/13688320/262854530-e5ae4e5e-38ec-4a8e-9675-86780465b904.png)
