### ISSUE TITLE
TODO: 图模型完善

### ISSUE THREAD

**Issue by szcf715** [szcf-weiya/ESL-CN#6]
结合http://ai.stanford.edu/~paskin/gm-short-course/， 完善有关 junction tree algorithm的问题。

**Comment by szcf-weiya** [comment]
Done! See the tip in [17.2 马尔科夫图及其性质](https://esl.hohoweiya.xyz/17-Undirected-Graphical-Models/17.2-Markov-Graphs-and-Their-Properties/index.html) for more details.
