### ISSUE TITLE
Tab 12.2

### ISSUE THREAD

**Issue by szcf-weiya** [szcf-weiya/ESL-CN#81]
![image](https://user-images.githubusercontent.com/13688320/36885950-f39e6a18-1e24-11e8-8186-12a18e49ebf8.png)

**Comment by szcf-weiya** [comment]
Done!
See [模拟：Tab. 12.2](https://esl.hohoweiya.xyz/notes/SVM/skin-of-the-orange/index.html) for details.

**Comment by hd0125** [comment]
您好，请问ESL中的练习部分将不会对外开放了吗

**Comment by szcf-weiya** [comment]
@hd0125 练习部分都在 issue 里面，如果已经解决了，会被 closed，但都是能查看的呀。如果想讨论，也是可以继续留言的。
